services:
  bot:
    image: t2bot:0.2
    volumes:
      - type: bind
        source: ./config/config.json
        target: /app/config/config.json
    build:
      context: .
      dockerfile: ./Dockerfile.Bot
    restart: always

  notifier:
    image: t2notif:0.2
    volumes:
      - type: bind
        source: ./config/config.json
        target: /app/config/config.json
    build:
      context: .
      dockerfile: ./Dockerfile.Notif
    restart: always
